const express = require('express');
const ProjectRouter = require('./projects/Router.js');
const ActionsRouter = require('./actions/Router.js');
const server = express();
const logger = require('./middleware/logger.js');
server.use(express.json());
server.get('/', logger, (req, res) => {res.send(`NO DATA AT ROOT - Get /api/projects`);});
server.use('/api/actions', logger, ActionsRouter);
server.use('/api/projects', logger, ProjectRouter);
module.exports = server;